import type { Metadata } from "next";
import { Catamaran } from "next/font/google";
import "../globals.css";

const catamaran = Catamaran({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	variable: "--font-catamaran",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={` ${catamaran.variable} font-catamaran antialiased`}>
				{children}
			</body>
		</html>
	);
}
