import type { Metadata } from "next";
import { Catamaran } from "next/font/google";
import SidePanel from "@/components/shared/SidePanel";
import NextTopLoader from "nextjs-toploader";
import "../globals.css";
import MobileHeader from "@/components/shared/MobileHeader";
import RootProvider from "@/components/shared/providers/RootProvider";
import Alert from "@/components/shared/Alert";
import { ApiInstance } from "@/utils";
import { cookies } from "next/headers";
import { ACCESS_TOKEN_COOKIE_NAME } from "@/constants";

const catamaran = Catamaran({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	variable: "--font-catamaran",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	let industries = [];
	let userDetails = null;

	const cookieStore = await cookies();
	if (cookieStore.has(ACCESS_TOKEN_COOKIE_NAME)) {
		const token = cookieStore.get(ACCESS_TOKEN_COOKIE_NAME)?.value;

		const response = await ApiInstance.get("/api/industries", {
			headers: {
				"auth-token": token,
			},
		});

		const userDetailsRes = await ApiInstance.get("/user/detail", {
			headers: {
				"auth-token": token,
			},
		});

		industries = response.data;
		userDetails = userDetailsRes.data;
	}

	return (
		<html lang="en">
			<body
				id="body"
				className={` ${catamaran.variable} font-catamaran antialiased flex flex-col lg:flex-row`}>
				<RootProvider industries={industries} userDetails={userDetails}>
					<NextTopLoader
						color="#ED3237"
						shadow="0 0 10px #ED3237,0 0 5px #ED3237"
					/>
					<Alert />
					<MobileHeader />
					<SidePanel />
					<main className="grow px-5 md:px-[25px] bg-[#F6F6F6] overflow-hidden">
						{children}
					</main>
				</RootProvider>
			</body>
		</html>
	);
}
