import type { Metadata } from "next";
import { Catamaran } from "next/font/google";
import SidePanel from "@/components/shared/SidePanel";
import NextTopLoader from "nextjs-toploader";
import "../globals.css";
import MobileHeader from "@/components/shared/MobileHeader";
import RootProvider from "@/components/shared/providers/RootProvider";
import Alert from "@/components/shared/Alert";

const catamaran = Catamaran({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	variable: "--font-catamaran",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={` ${catamaran.variable} font-catamaran antialiased flex flex-col lg:flex-row`}>
				<RootProvider>
					<NextTopLoader
						color="#ED3237"
						shadow="0 0 10px #ED3237,0 0 5px #ED3237"
					/>
					<Alert />
					<MobileHeader />
					<SidePanel />
					<main className="grow px-5 md:px-[25px] bg-[#F6F6F6]">
						{children}
					</main>
				</RootProvider>
			</body>
		</html>
	);
}
